const ReducerActions = {
  GET_TRANSACTION: 'GET_TRANSACTION',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',
}

export default ReducerActions
