const ReducerActions = {
  // TRNSACTION
  GET_TRANSACTION: 'GET_TRANSACTION',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',
  MAKE_TRANSACTION: 'MAKE_TRANSACTION',
  MAKE_TRANSACTION_SUCCESS: 'MAKE_TRANSACTION_SUCCESS',
  MAKE_TRANSACTION_FAILED: 'MAKE_TRANSACTION_FAILED',
  MAKE_TRANSACTION_RESET: 'MAKE_TRANSACTION_RESET',
  INSERT_TRANSACTION: 'INSERT_TRANSACTION',
  // BENEFICIARY
  GET_BENEFICIARY: 'GET_BENEFICIARY',
  GET_BENEFICIARY_SUCCESS: 'GET_BENEFICIARY_SUCCESS',
  GET_BENEFICIARY_FAILED: 'GET_BENEFICIARY_FAILED',
}

export default ReducerActions
