const ReducerActions = {
  // TRNSACTION
  GET_TRANSACTION: 'GET_TRANSACTION',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',
  // BENEFICIARY
  GET_BENEFICIARY: 'GET_BENEFICIARY',
  GET_BENEFICIARY_SUCCESS: 'GET_BENEFICIARY_SUCCESS',
  GET_BENEFICIARY_FAILED: 'GET_BENEFICIARY_FAILED',
}

export default ReducerActions
